### ISSUE TITLE
Invalid request body

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/produce#111]
Crash report: 9d17043d795f9d58f2823046ce83ede4 - "invalid request body"

When i call this code with create_itc = true it fails with the above crash, but when I call it with to create devcenter it works fine:

```
def produce_app(create_itc, create_developer_account)
  produce(
    username: ENV["APPLE_ID"],
    app_identifier: ENV["APP_IDENTIFIER"],
    language: "Danish",
    app_version: ENV["APP_VERSION_NUMBER"],
    app_name: ENV["APP_TITLE"],
    sku: "1234567890xxx",
    skip_itc: !create_itc,
    skip_devcenter: !create_developer_account,
    team_name: "xxx")  
end
```

I can't figure out what is wrong with it.

**Comment by vpolouchkine** [comment]
Can you please post the full log and the version you're currently using?

**Comment by mortenholmgaard** [comment]
I don't know what else to post - Can't you see the that in the crash report?
I am using latest version

**Comment by mortenholmgaard** [comment]
@vpolouchkine will you have a look at it?

**Comment by vpolouchkine** [comment]
Can you run `sudo gem update spaceship` so you're on latest?

**Comment by mortenholmgaard** [comment]
I can't really test this right now because it had to release the version manually, and now I kind of need to wait to next time we are ready to release a version..
