### ISSUE TITLE
Any way to specify prefix?

### ISSUE THREAD

**Issue by minwoolee** [fastlane/produce#118]
Is there any way to specify app prefix? Thanks.

**Comment by i2amsam** [comment]
@minwoolee could you expand a bit more in what you're trying to accomplish?

**Comment by minwoolee** [comment]
@i2amsam when registering an app ID, it's possible to specify a prefix. This does not seem possible with produce. Thanks.

![register](https://cloud.githubusercontent.com/assets/178365/13000310/b2710200-d10d-11e5-8514-6c65311b6b02.jpg)
