### ISSUE TITLE
App already exists

### ISSUE THREAD

**Issue by woutergoossens** [fastlane/produce#19]
Hi,

I am trying to add a new application with produce but I am getting the warning message that my app already exists. But that name is not yet used.. Tried with several application names and always the same message. Any idea?

Thanks

Logs:
INFO [2015-03-10 16:03:00.52]: Login into iOS Developer Center
INFO [2015-03-10 16:03:11.67]: Login successful
App Name: Find your Mojo
INFO [2015-03-10 16:03:17.04]: App 'Find your Mojo' already exists, nothing to do on the Dev Center
INFO [2015-03-10 16:03:17.04]: Logging into iTunesConnect
INFO [2015-03-10 16:03:27.38]: Successfully logged into iTunesConnect
INFO [2015-03-10 16:03:45.35]: App 'Find your Mojo' exists already, nothing to do on iTunes Connect

Screenshot:
![screen shot 2015-03-10 at 16 08 29](https://cloud.githubusercontent.com/assets/355048/6577649/c56710e4-c73f-11e4-87c7-2eb326182e46.png)

**Comment by KrauseFx** [comment]
Does that happen every time you use `produce`? Did it work before? 

Open iTunes Connect and click the + Icon on the top left. Does your app appear in the dropdown?

Can you try with a different app identifier and app name?

**Comment by woutergoossens** [comment]
It is the first time I want to use it.

It does not appear when I click the + icon in iTunes Connect so the app is not created and does not exist in iTunes Connect.

I am starting produce but it is only asking for me the app name and then it gives the warning. How can I start produce that it asks for the app identifier?

Thanks!

MacBook-Pro-Retina-Wouter:Else woutergoossens$ produce -u *****
INFO [2015-03-10 18:20:02.01]: Login into iOS Developer Center
INFO [2015-03-10 18:20:12.63]: Login successful
App Name: Find your Mojo
INFO [2015-03-10 18:20:24.98]: App 'Find your Mojo' already exists, nothing to do on the Dev Center
INFO [2015-03-10 18:20:24.98]: Logging into iTunesConnect

**Comment by KrauseFx** [comment]
I tried it and it worked perfectly fine. I'll need more information. Are you running `produce` in a directory with a `fastlane` folder?

**Comment by woutergoossens** [comment]
Yeah that's it! When I run it from another directory it asks for the app identifier

Thanks

**Comment by KrauseFx** [comment]
I'll leave this issue open. I guess it doesn't make sense to fetch the information from the Appfile for `produce`. Thanks for letting me know.

**Comment by KrauseFx** [comment]
Have you tried the latest version?

**Comment by shoshRose** [comment]
I get the same message for the developer center. but an error when from iTunes Connect:
(The app does NOT exist on Dev Center)
How can this be resolved?

[11:00:23](---------------------): --- Step: produce ---

Logging spaceship web requests to '/tmp/spaceship.log'
[11:00:30]: App 'paShosh' already exists, nothing to do on the Dev Center
[11:00:32]: Logging into iTunesConnect
[11:00:51]: Successfully logged into iTunesConnect
[11:01:05]: Creating new app 'paShosh' on iTunes Connect
.
.
[11:01:40]: Couldn't find element 'option[value='com.domain.paShosh']' after waiting for quite some time
[11:01:41]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.8.0/lib/fastlane_core/itunes_connect/itunes_connect_helper.rb:76:in `wait_for_elements': Couldn't find element 'option[value='com.domain.paShosh']' after waiting for quite some time (FastlaneCore::ItunesConnect::ItunesConnectGeneralError)

**Comment by KrauseFx** [comment]
@shoshRose @woutergoossens Take a look at https://github.com/fastlane/produce/pull/49 @mathcarignani is working on a cool upgrade of `produce` :+1:

**Comment by shoshRose** [comment]
thnx my issue has been resolved.

**Comment by KrauseFx** [comment]
@shoshRose it has been resolved with the pull request?

**Comment by shoshRose** [comment]
no, my bad..
I had an issue in the Appfile
