### ISSUE TITLE
I have literally thousand apps, and the script can't find the app it has just created and crashes

### ISSUE THREAD

**Issue by ericertl** [fastlane/produce#26]
```
/Library/Ruby/Gems/2.0.0/gems/produce-0.1.6/lib/produce/developer_center.rb:43:in `create_new_app': Something went wrong when creating the new app - it's not listed in the App's list (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.1.6/lib/produce/developer_center.rb:10:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.1.6/lib/produce/manager.rb:7:in `start_producing'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.1.6/bin/produce:34:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.1.6/bin/produce:47:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.1.6/bin/produce:51:in `<top (required)>'
    from /usr/bin/produce:23:in `load'
    from /usr/bin/produce:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Ha, I guess that's because you have thousands apps! When you open the App IDs list on the Apple Developer Portal, do you see all app IDs? Do you have to click somewhere to see all?

**Comment by ericertl** [comment]
The portal doesn't load all appids at once.
I have either to scroll a lot and the list populates dynamically or search for the name (which is faster)

**Comment by ericertl** [comment]
In an ideal world, if the appid name search fails, it should try to do a search?

**Comment by KrauseFx** [comment]
Yes, exactly. Or it could use the new API https://github.com/KrauseFx/sigh/pull/72 :+1:

**Comment by ericertl** [comment]
That would be even better. Nice job man. I'm using snapshot and deliver, and they made work like a charm

**Comment by KrauseFx** [comment]
@ericertl Can you try the latest version and let me know if that works for you? :+1:

**Comment by ericertl** [comment]
Error while creating the app id (which is not listed in the first page) on dev center is gone! WOOT!!
I'll test the itunes connect part and leave you more comments

[08:26:09](---------------------): --- Step: default_platform ---

[08:26:09](---------------------): Driving the lane 'ios devCenter'

[08:26:09](---------------------): --- Step: produce ---

Logging spaceship web requests to '/tmp/spaceship.log'
[08:26:18]: Creating new app 'XXXXXXXXXXXXX' on the Apple Dev Center
[08:26:20]: Created app #Spaceship::App:0x007ff3da990a18
[08:26:24]: Finished creating new app 'XXXXXXXXXXXXX' on the Dev Center
[08:26:26]: fastlane.tools finished successfully 🎉

**Comment by ericertl** [comment]
Unfortunately creating the app on itunes connect still throws the same error :.(
(but that's on another issue ticket, so this one can be closed)
