### ISSUE TITLE
I can't create a new app in itc

### ISSUE THREAD

**Issue by ericertl** [fastlane/produce#31]
I created a lane skipping devcenter and just focusing on create the app in itc, but I'm getting this error:

```
FATAL [2015-04-22 12:31:19.52]: Capybara::Poltergeist::MouseEventFailed
FATAL [2015-04-22 12:31:21.03]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/node.rb:23:in `rescue in command': Firing a click at co-ordinates [-9910.5, 162.5] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click'). (Capybara::Poltergeist::MouseEventFailed)
```

**Comment by KrauseFx** [comment]
Sorry for the delayed reply. Do you still experience this problem?

**Comment by ericertl** [comment]
I can try again, but I didn't see any update for this gem

**Comment by ericertl** [comment]
I'm still experiencing this. 
For this error (Firing a click at co-ordinates [-9910.5, 162.5] failed.), I think the issue might be either due to my mac resoultion or for the tons of apps I have in ITC.

FATAL [2015-05-06 18:49:58.86]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/node.rb:23:in `rescue in command': Firing a click at co-ordinates [-9910.5, 162.5] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click'). (Capybara::Poltergeist::MouseEventFailed)

![error1430948995png](https://cloud.githubusercontent.com/assets/777783/7504913/31ec5ccc-f424-11e4-91f5-4a76650b8e2c.png)

**Comment by osrufung** [comment]
same error here... 

Tons of Apps in my ITC account... :( 

any fix?

**Comment by osrufung** [comment]
Same bug (randomly appears) in 0.3.2 version of Produce 😕
