### ISSUE TITLE
Make an option to tick "Associated Domains" in dev.🍎.com

### ISSUE THREAD

**Issue by alistra** [fastlane/produce#53]
I have about 400 apps in developer.apple.com and due to a recent lawsuit I have to enable "Associated Domains" on all of them.

It would be cool if produce supported providing options to generated identifiers, as some options require mobileprovision regeneration, so the best idea is to tick the options right away.

**Comment by KrauseFx** [comment]
This will require an addition to `spaceship` to make this possible.
