### ISSUE TITLE
Error on produce step

### ISSUE THREAD

**Issue by gianghd** [fastlane/produce#70]
Here is my logs.
Maybe ithis problem is "Unauthorized access" but I don't know how to fix it. 

```
trungnts-Mac-Pro:fastlane trungnt$ fastlane submit
[09:49:02]: -------------------------------------------------
[09:49:02]: --- Step: Verifying required fastlane version ---
[09:49:02]: -------------------------------------------------
[09:49:02]: fastlane version valid
[09:49:02]: ------------------------------
[09:49:02]: --- Step: default_platform ---
[09:49:02]: ------------------------------
[09:49:02]: Driving the lane 'ios submit' 🚀
[09:49:02]: ---------------------
[09:49:02]: --- Step: produce ---
[09:49:02]: ---------------------
[09:49:06]: Creating new app 'Bo him Xuan Thanh' on the Apple Dev Center
[09:49:07]: Created app TK8NBX53QH
[09:49:08]: Finished creating new app 'Bo him Xuan Thanh' on the Dev Center
[09:49:10]: Variable Dump:
[09:49:10]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios submit"}
[09:49:10]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | produce                             | 7           |
+------+-------------------------------------+-------------+

[09:49:10]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.0/lib/spaceship/client.rb:241:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
```

**Comment by Srthk** [comment]
It was working till yesterday. Getting the same error from today-

```
[13:36:15]: ---------------------
[13:36:15]: --- Step: produce ---
[13:36:15]: ---------------------
[13:36:35]: Creating new app 'Pizza Hut Bake' on the Apple Dev Center
[13:36:37]: Created app 9EU97ART8J
[13:36:41]: Finished creating new app 'Pizza Hut Bake' on the Dev Center
[13:36:43]: Variable Dump:
[13:36:43]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy"}
[13:36:43]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | produce                             | 27          |
+------+-------------------------------------+-------------+

[13:36:43]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.0/lib/spaceship/client.rb:241:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.0/lib/spaceship/tunes/tunes_client.rb:128:in `applications'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.0/lib/spaceship/tunes/application.rb:63:in `all'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.0/lib/spaceship/tunes/application.rb:69:in `find'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/itunes_connect.rb:43:in `fetch_application'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/itunes_connect.rb:16:in `create_new_app'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/itunes_connect.rb:12:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/manager.rb:6:in `start_producing'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/actions/produce.rb:20:in `block in run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/actions/produce.rb:18:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/actions/produce.rb:18:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:127:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:127:in `execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/fast_file.rb:120:in `method_missing'
    from (eval):64:in `block (3 levels) in parse'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/lane.rb:36:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/lane.rb:36:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:50:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:44:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/runner.rb:44:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/bin/fastlane:35:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/bin/fastlane:124:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.17.0/bin/fastlane:130:in `<top (required)>'
    from /usr/bin/fastlane:23:in `load'
    from /usr/bin/fastlane:23:in `<main>'
```

**Comment by SPAHI4** [comment]
same error too

**Comment by robwithhair** [comment]
@KrauseFx same error here too

**Comment by robwithhair** [comment]
```
[37m[10:03:59]: [0m[32m---------------------[0m
[37m[10:03:59]: [0m[32m--- [0m[32mStep: produce[0m[32m ---[0m
[37m[10:03:59]: [0m[32m---------------------[0m
[37m[10:04:04]: [0m[32m[DevCenter] App 'Granville's Farm Shop' already exists, nothing to do on the Dev Center[0m
[37m[10:04:05]: [0m[33mVariable Dump:[0m
[37m[10:04:05]: [0m{:ENVIRONMENT=>nil, :PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :BUILD_NUMBER=>0}
[1m[31m[10:04:05]: [0m[0m{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | increment_build_number              | 0           |
| 3    | produce                             | 5           |
+------+-------------------------------------+-------------+

[1m[31m[10:04:05]: [0m[0m[31mfastlane finished with errors[0m
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.4.0/lib/spaceship/client.rb:239:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.4.0/lib/spaceship/tunes/tunes_client.rb:129:in `applications'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.4.0/lib/spaceship/tunes/application.rb:63:in `all'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.4.0/lib/spaceship/tunes/application.rb:69:in `find'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/itunes_connect.rb:43:in `fetch_application'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/itunes_connect.rb:16:in `create_new_app'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/itunes_connect.rb:12:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/manager.rb:6:in `start_producing'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/actions/produce.rb:20:in `block in run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/actions/produce.rb:18:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/actions/produce.rb:18:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:127:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:127:in `execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/fast_file.rb:120:in `method_missing'
    from (eval):36:in `block (2 levels) in parse'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/lane.rb:32:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/lane.rb:32:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:50:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:44:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/runner.rb:44:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/bin/fastlane:35:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/bin/fastlane:124:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.16.0/bin/fastlane:130:in `<top (required)>'
    from /usr/bin/fastlane:23:in `load'
    from /usr/bin/fastlane:23:in `<main>'

[32m#######################################################################[0m
[32m# fastlane 1.17.0 is available. You are on 1.16.0.[0m
[32m# It is recommended to use the latest version.[0m
[32m# Update using 'sudo gem update fastlane'.[0m
[32m# To see what's new, open https://github.com/KrauseFx/fastlane/releases.[0m
[32m#######################################################################[0m
Build step 'Execute shell' marked build as failure
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
Finished: FAILURE
```

Currently pulling new version of fastlane

**Comment by robwithhair** [comment]
Updated fastlane, still seeing bug

**Comment by robwithhair** [comment]
Attempting to manually create app in itunes connect

**Comment by KrauseFx** [comment]
Working on it right now :+1:

**Comment by robwithhair** [comment]
Awesome thanks Felix.  Can confirm that it still fails if I manually create app in iTC.

**Comment by robwithhair** [comment]
if it's any help...

```
# Logfile created on 2015-08-14 09:55:11 +0100 by logger.rb/41954
[09:55:11]: POST: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wo/0.0.1.15.3.13.3.2.1.1.3.1.1 {theAccountName: reddiceapps@gmail.com}
[09:55:20]: POST: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wo/0.0.1.15.3.13.3.2.1.1.3.1.1: 
[09:55:20]: GET: ra/apps/manageyourapps/summary 
[09:55:20]: GET: ra/apps/manageyourapps/summary: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unauthorized access"]}, "statusCode"=>"ERROR"}
```

**Comment by KrauseFx** [comment]
I can reproduce the error, thanks

**Comment by gianghd** [comment]
Should I update gem ?

**Comment by KrauseFx** [comment]
Found the issue, will push it in a few minutes

**Comment by KrauseFx** [comment]
No, it's not yet live

**Comment by KrauseFx** [comment]
Please update using `sudo gem update spaceship` and let me know if that works for you.

**Comment by robwithhair** [comment]
All hail @KrauseFx!  Thanks Felix.  We are past produce and on to the rest of the script.

**Comment by KrauseFx** [comment]
@robwithhair so it's working for you?

**Comment by robwithhair** [comment]
Script still running but yes, so far

**Comment by robwithhair** [comment]
Script succeeded. All good @KrauseFx.

**Comment by robwithhair** [comment]
@KrauseFx however, just tested with an app which didn't already exist it iTC and it failed!  Same place.

**Comment by robwithhair** [comment]
@KrauseFx worked fine on third try?  How odd.

**Comment by Srthk** [comment]
I am still receiving the same error on `produce` after updating spaceship. Have you pushed a gem update for fastlane too?

**Comment by robwithhair** [comment]
@Srthk yes I believe one of my servers wasn't up to date.  Seems to be working now for me but had to update fastlane too.

**Comment by KrauseFx** [comment]
@Srthk are you using `bundler`? If so, you'll have to run `bundle update`

**Comment by Srthk** [comment]
Error solved. `produce` worked on updating `sudo gem update fastlane`

**Comment by gianghd** [comment]
Thank @KrauseFx . With my app, run OK. No problem after update spaceship.

**Comment by KrauseFx** [comment]
Thanks everybody :+1:

**Comment by SPAHI4** [comment]
still have this error after update

**Comment by Srthk** [comment]
@SPAHI4 Try updating spaceship as well using `sudo gem update spaceship`

**Comment by SPAHI4** [comment]
@Srthk I've tried

**Comment by SPAHI4** [comment]
Now all ok, dont know whats happend

**Comment by robwithhair** [comment]
@KrauseFx I just had a build fail with this same issue when the version number was too low.  Don't know if it was related but seems to be failing like this every so often perhaps.

**Comment by robwithhair** [comment]
@KrauseFx we rebuilt with exact same parameters and it succeeded this time.  Must be an intermittent issue at iTC's end maybe.

**Comment by robwithhair** [comment]
@KrauseFx we are seeing this bug again this morning.  Builds failing with the same error message.

**Comment by shoshRose** [comment]
me too

**Comment by robwithhair** [comment]
@KrauseFx The build seemed to work on 3rd attempt.  Possibly down to time required for bundle ID to propagate to iTC?  Possibly an issue at apple's end? Seems really odd.

**Comment by robwithhair** [comment]
@KrauseFx consistently failing again.  Could you re-open this issue?

**Comment by Srthk** [comment]
Yes same issue is occurring again.

**Comment by Srthk** [comment]
@KrauseFx When will this be resolved?

**Comment by KrauseFx** [comment]
I have to say, the login is working perfectly fine for me. I assume you checked the user credentials are correct? 

I'll work on a new version of `spaceship` that shows more debug information if the login isn't working, like the used username, the exact response and more.

**Comment by robwithhair** [comment]
We've had this issue sporadically while building.  It seemed like manually creating the version on iTC made the build work again.

**Comment by robwithhair** [comment]
Of course could be nothing to do with that and could be intermittent but I have found twice now manually creating the app on iTC made the build script run.

**Comment by robwithhair** [comment]
@KrauseFx one's we built were re-builds through jenkins so same user/pass each time.

**Comment by robwithhair** [comment]
At one point I thought it might be to do with the time it takes for the bundle ID to propagate from dev centre to iTC but other failures don't fit that.

**Comment by gfpacheco** [comment]
Just saying, I'm having this issue sporadically as well

**Comment by Srthk** [comment]
@KrauseFx The username and login credentials are absolutely correct because its working with the same details but producing the above mentioned error intermittently. How was this issue resolved earlier, please try to fix it in the same manner.

**Comment by KrauseFx** [comment]
I just pushed a new release https://github.com/fastlane/spaceship/releases/tag/0.5.2, please update using `sudo gem update spaceship`, special thanks to @sunboshan for helping me resolve this issue via https://github.com/fastlane/spaceship/issues/93

Please let me know if that works for you :+1:

**Comment by UnGun** [comment]
I successfully created a new app onto Itunes about 3 hours ago.  But when I tried again just now it failed with this error message:

{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appCreate", :SNAPSHOT_SCREENSHOTS_PATH=>"/Users/shie1985/meepshop/mobileApp/code/platforms/ios/fastlane/screenshots", :CERT_FILE_PATH=>"./U22R4QWNDD.cer", :CERT_CERTIFICATE_ID=>"U22R4QWNDD"}
[13:29:07]: {"responseId"=>"13a69736-e94d-4aec-b781-a5b46703a127", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"No value was provided for the parameter &#x27;appIdName&#x27;.", "creationTimestamp"=>"2015-08-19T05:29:26Z", "protocolVersion"=>"QH65B2", "requestId"=>"", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com:443//services-account/QH65B2/account/ios/identifiers/addAppId.action", "httpCode"=>200, "errorMessagesForXcode"=>nil, "suppressed"=>[], "validationMessages"=>[{"validationKey"=>"appIdName", "validationUserMessage"=>"No value was provided for the parameter &#x27;appIdName&#x27;."}]}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |å
| 2    | default_platform                    | 0           |
| 3    | snapshot                            | 303         |
| 4    | cert                                | 21          |
| 5    | produce                             | 3           |
+------+-------------------------------------+-------------+

[13:29:07]: fastlane finished with errors

#######################################################################
# fastlane 1.18.0 is available. You are on 1.13.1.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
# To see what's new, open https://github.com/KrauseFx/fastlane/releases.
#######################################################################
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.2/lib/spaceship/client.rb:241:in `parse_response': {"responseId"=>"13a69736-e94d-4aec-b781-a5b46703a127", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"No value was provided for the parameter &#x27;appIdName&#x27;.", "creationTimestamp"=>"2015-08-19T05:29:26Z", "protocolVersion"=>"QH65B2", "requestId"=>"", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com:443//services-account/QH65B2/account/ios/identifiers/addAppId.action", "httpCode"=>200, "errorMessagesForXcode"=>nil, "suppressed"=>[], "validationMessages"=>[{"validationKey"=>"appIdName", "validationUserMessage"=>"No value was provided for the parameter &#x27;appIdName&#x27;."}]} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.2/lib/spaceship/portal/portal_client.rb:163:in `create_app!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.2/lib/spaceship/portal/app.rb:96:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/developer_center.rb:23:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/developer_center.rb:9:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.0/lib/produce/manager.rb:5:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/produce.rb:20:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/produce.rb:18:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/produce.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):54:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.13.1/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by Srthk** [comment]
`produce` is working fine for now. Hope this error doesn't crop up again :smile:

**Comment by KrauseFx** [comment]
@UnGun this is a different error that doesn't have anything to do with the login issue. Could you submit a separate issue?

**Comment by KrauseFx** [comment]
@Srthk Great to hear :rocket:
