### ISSUE TITLE
Getting SSL_CONNECT SYSCALL error with "Produce"

### ISSUE THREAD

**Issue by NikhilRyan** [fastlane/produce#72]
Yesterday I updated fastlane and since then i'm getting this error.
![screen shot 2015-08-25 at 10 03 32 am](https://cloud.githubusercontent.com/assets/13447764/9458786/9d418e00-4b10-11e5-80e2-a38d16d2b128.png)

**Comment by KrauseFx** [comment]
This shouldn't have anything to do with the updated version of `fastlane`, but an SSL issue: https://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read

Maybe even related to https://github.com/fastlane/spaceship/issues/54#issuecomment-134377306

cc @lacostej

**Comment by robwithhair** [comment]
Yes, exactly the same as what we've been seeing at our end.  See issue Felix referenced.
