### ISSUE TITLE
iCloud with CloudKit - Service Enables but Container not Creating 

### ISSUE THREAD

**Issue by shahbazali** [fastlane/produce#83]
Hello, I'm sorry to disturbed you again but its not working for me (Command Works but not creating iCloud Container), as i am using

produce enable_services --icloud cloudkit

that works fine, but the issue is iCloud Container is not creating through this command, it give message 1 Service Enabled Successfully, but when i go to Developer Portal iCloud always says Configurable because Container is not created.

Please Help

thanks in advance.

**Comment by bencollier** [comment]
We're having this problem too - current workaround is to manually login to the dev centre then do the iCloud Container Assignment yourself and re-run produce. Not ideal though.

It'd be great to see produce have the ability to hit that [Edit] button on the iCloud setting to add a new container on the App ID Settings screen.

![Dev Center Image](https://www.dropbox.com/s/94ekf97thj8uy6o/Screenshot%202015-10-27%2022.08.18.png?dl=1)

**Comment by shahbazali** [comment]
Any Luck ? ? ?

**Comment by shahbazali** [comment]
Hello, PLEASE Help Me. i want to create iCloud Container

**Comment by chaffeqa** [comment]
I dont think spaceship has the api for creating a cloudkit yet.

May be useful to do the same as the app groups as with cloudkit
